export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as About } from './About'
export {default as ErrorPage} from './404'
export {default as Article} from './Article'
export {default as Dashboard} from './Dashboard'